/* eslint-disable camelcase */
// Minimal mock WebGLRenderingContext for tests that construct a real
// WebGLInstance / GLObject over a fake GL context. Shared by GLObject.test.ts
// and FigurePrimitives.glMask.test.ts (see also webgl.context.test.ts).
//
// Note: getProgramParameter / getShaderParameter always return true, so this
// mock cannot catch malformed shader source - shader composition is verified
// separately in shaders.test.ts.
export default function createMockGL() {
  return {
    TRIANGLES: 4,
    TRIANGLE_STRIP: 5,
    TRIANGLE_FAN: 6,
    LINES: 1,
    LINK_STATUS: 0x8B82,
    VERTEX_SHADER: 0x8B31,
    COMPILE_STATUS: 0x8B81,
    FRAGMENT_SHADER: 0x8B30,
    SRC_ALPHA: 0x0302,
    ONE: 1,
    ONE_MINUS_SRC_ALPHA: 0x0303,
    BLEND: 0x0BE2,
    COLOR_BUFFER_BIT: 0x4000,
    TEXTURE_2D: 0x0DE1,
    RGBA: 0x1908,
    UNSIGNED_BYTE: 0x1401,
    TEXTURE_WRAP_S: 0x2802,
    CLAMP_TO_EDGE: 0x812F,
    TEXTURE_WRAP_T: 0x2803,
    TEXTURE_MIN_FILTER: 0x2801,
    LINEAR: 0x2601,
    ARRAY_BUFFER: 0x8892,
    STATIC_DRAW: 0x88E4,
    FLOAT: 0x1406,
    UNPACK_PREMULTIPLY_ALPHA_WEBGL: 0x9241,
    UNPACK_FLIP_Y_WEBGL: 0x9240,
    TEXTURE0: 0x84C0,
    DEPTH_TEST: 0x0B71,
    RENDERBUFFER: 0x8D41,
    FRAMEBUFFER: 0x8D40,
    COLOR_ATTACHMENT0: 0x8CE0,
    DEPTH_ATTACHMENT: 0x8D00,
    DEPTH_COMPONENT16: 0x81A5,
    MAX_TEXTURE_SIZE: 0x0D33,
    REPEAT: 0x2901,
    drawingBufferWidth: 100,
    drawingBufferHeight: 100,
    createBuffer: jest.fn(() => ({})),
    deleteBuffer: jest.fn(),
    bindBuffer: jest.fn(),
    bufferData: jest.fn(),
    enableVertexAttribArray: jest.fn(),
    vertexAttribPointer: jest.fn(),
    disableVertexAttribArray: jest.fn(),
    uniformMatrix3fv: jest.fn(),
    uniformMatrix4fv: jest.fn(),
    uniform4f: jest.fn(),
    uniform1f: jest.fn(),
    uniform1i: jest.fn(),
    uniform3fv: jest.fn(),
    texParameteri: jest.fn(),
    drawArrays: jest.fn(),
    clearColor: jest.fn(),
    clear: jest.fn(),
    createTexture: jest.fn(() => ({})),
    activeTexture: jest.fn(),
    bindTexture: jest.fn(),
    pixelStorei: jest.fn(),
    texImage2D: jest.fn(),
    blendFunc: jest.fn(),
    attachShader: jest.fn(),
    linkProgram: jest.fn(),
    getProgramParameter: jest.fn(() => true),
    getProgramInfoLog: jest.fn(() => ''),
    createProgram: jest.fn(() => ({ id: 'program' })),
    deleteProgram: jest.fn(),
    createShader: jest.fn(type => ({ type })),
    shaderSource: jest.fn(),
    compileShader: jest.fn(),
    getShaderParameter: jest.fn(() => true),
    getAttribLocation: jest.fn(() => 0),
    getUniformLocation: jest.fn(() => ({})),
    enable: jest.fn(),
    disable: jest.fn(),
    deleteShader: jest.fn(),
    useProgram: jest.fn(),
    viewport: jest.fn(),
    generateMipmap: jest.fn(),
    deleteTexture: jest.fn(),
    getParameter: jest.fn(() => 4096),
    getExtension: jest.fn(() => ({ loseContext: jest.fn() })),
    createRenderbuffer: jest.fn(() => ({})),
    bindRenderbuffer: jest.fn(),
    createFramebuffer: jest.fn(() => ({})),
    bindFramebuffer: jest.fn(),
    framebufferTexture2D: jest.fn(),
    framebufferRenderbuffer: jest.fn(),
    renderbufferStorage: jest.fn(),
    canvas: {
      toDataURL: () => '',
      width: 100,
      clientWidth: 100,
      clientHeight: 100,
      height: 100,
      style: { top: 0, visibility: 'visible' },
    },
  };
}
