const figure = new Fig.Figure({
  limits: [-1.5, -1.5, 3, 3],
  color: [1, 0, 0, 1],
  lineWidth: 0.01,
  font: { size: 0.1 },
});

// Add name and element
const [collection] = figure.add({ method: 'collection' });
const element = figure.primitives.polygon({ radius: 1 });
collection.add('name', element);

// Element only (name will be autogenerated)
const [collection] = figure.add({ method: 'collection' });
const element = figure.primitives.polygon({ radius: 1 });
collection.add(element);

// Element definition (if no name is provided, then name will
// be auto generated)
const [collection] = figure.add({ method: 'collection' });
collection.add({
  method: 'polygon',
  options: { radius: 1 },
});

// Array
const [collection] = figure.add({ method: 'collection' });
const element = figure.primitives.polygon({ radius: 1 });
collection.add([
  element,
  {
    method: 'polygon',
    options: { radius: 0.2, color: [0, 0, 1, 1] },
  },
]);
